#!/bin/bash

# Handle command line args
if [[ -z $1 || -z $2 ]]
then
    echo "ERROR: no grouping IP specified."
    echo "Usage: ./aggregate_and_sort <path> <src/dst>"
    echo "ARGS:"
    echo "  path:    path to the ctu13 dataset"
    echo "  src/dst: whether to group by source or destination IP addresses"
    exit
fi

data_path=$(echo "$1" | tr -d '/')
# Grouping is the index key to group on when we sort the aggregated file
grouping=2
if [ "$2" = "dst" ]
then
    grouping=3
fi

agg_file="aggregate.txt"
sort_file="sorted_aggregate.txt"

if [ -f $agg_file ]
then
    rm $agg_file
fi

# Aggregate all data into a single text file
for file in $(find $data_path -name merged.txt)
do
    cat $file >> $agg_file
done

if [ ! -f $agg_file ]
then
    echo "ERROR: No merged data files found."
    echo "Did you run the merging vast and features pipeline?"
    exit
fi

# Group by IP address and then sort the groupings by time stamp
sort -t ',' -k "$grouping","$grouping" -k 1,1 -s $agg_file > $sort_file
